git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "c"
    prompts:
      - type: "menu"
        title: "What kind of commit is it?"
        options:
          - name: "feat"
            description: "a feature commit"
            value: "feat"
          - name: "fix"
            description: "a fix commit"
            value: "fix"
          - name: "dep"
            description: "a dependency"
            value: "dep"
          - name: "refactor"
            description: "a refactor"
            value: "refactor"
          - name: "test"
            description: "a test"
            value: "test"
          - name: "build"
            description: "a build change"
            value: "build"
          - name: "docs"
            description: "a doc change"
            value: "docs"
          - name: "ci"
            description: "a ci change"
            value: "ci"
          - name: "style"
            description: "a code style change"
            value: "style"
      - type: "input"
        title: "What is the commit message?"
        initialValue: ""
    command: 'git commit -m "{{index .PromptResponses 0}}: {{index .PromptResponses 1}}"'
    context: "files"
  - key: "b"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        options:
          - name: "feature"
            description: "a feature branch"
            value: "feature"
          - name: "test"
            description: "a test branch"
            value: "test"
          - name: "fix"
            description: "a fix branch"
            value: "fix"
          - name: "release"
            description: "a release branch"
            value: "release"
          - name: "documentation"
            description: "a branch for documentation"
            value: "documentation"
      - type: "input"
        title: "What is the Jira ticket number?"
      - type: "input"
        title: "What is the PR description?"
        initialValue: ""
    command: "bash $HOME/.config/lazygit/pr.sh '{{index .PromptResponses 0}}' '{{index .PromptResponses 1}}' '{{index .PromptResponses 2}}'"
    context: "global"
  - key: "v"
    command: "gh pr view --web"
    context: "localBranches"
